---
title: "gbm_Scripts_survival"
author: "Jing"
date: "2025-01-16"
output: html_document
---

```{r setup, include=FALSE}
library(survival)
library(survminer)
library(dplyr)
library(ggplot2)
library(stringr)
library(readxl)


wkdir<- ("/home/jing/Phd_project/project_GBM/gbm_DATA/")
outdir<- ('/home/jing/Phd_project/project_GBM/gbm_OUTPUT/gbm_OUTPUT_survival/')
```

```{r TCGA}
#clin
tcga_clin_raw <- read.delim(paste0(wkdir,"gbm_DATA_TCGA/data_clinical_patient.txt"), 
                       sep = '\t',skip = 4,row.names = 'PATIENT_ID')

#clin profiles
clin_sample <- read.delim(paste0(wkdir,"gbm_DATA_TCGA/data_clinical_sample.txt"), sep = '\t',skip = 4)
table(clin_sample$SAMPLE_TYPE)
recurrent <-clin_sample[clin_sample$SAMPLE_TYPE=="Recurrence",]
recurrent$PATIENT_ID

tcga_clin_raw$SAMPLE_TYPE ="Primary"
tcga_clin_raw[recurrent$PATIENT_ID,]$SAMPLE_TYPE='Recurrence'
table(tcga_clin_raw$SAMPLE_TYPE)

tcga_clin_raw <-tcga_clin_raw[tcga_clin_raw$SAMPLE_TYPE=='Primary',]
tcga_clin_raw <-tcga_clin_raw[tcga_clin_raw$SUBTYPE=='GBM_IDHwt',]
tcga_clin_raw <- tcga_clin_raw[tcga_clin_raw$SEX != "", ]

#RNA
tcga_RNA_raw <- read.delim(paste0(wkdir,"gbm_DATA_TCGA/data_mrna_seq_v2_rsem_zscores_ref_all_samples.txt"),check.names = FALSE)
tcga_RNA_raw[is.na(tcga_RNA_raw)] <- 0
tcga_RNA_raw <- tcga_RNA_raw[tcga_RNA_raw$Hugo_Symbol!='',]
tcga_RNA_raw <- tcga_RNA_raw[!duplicated(tcga_RNA_raw$Hugo_Symbol),]
rownames(tcga_RNA_raw) <- tcga_RNA_raw$Hugo_Symbol
tcga_RNA <- as.data.frame(t(tcga_RNA_raw[-1:-2]))

# Align clinical data:
tcga_clin <- tcga_clin_raw[row.names(tcga_clin_raw)%in% str_sub(row.names(tcga_RNA), end = -4),]
tcga_RNA <- tcga_RNA[str_sub(row.names(tcga_RNA), end = -4) %in% row.names(tcga_clin_raw), ]
```

```{r CGGA 693}
clin_693_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_693_clinical.20200506.txt"), sep = '\t')
clin_693 <- clin_693_raw[clin_693_raw$PRS_type =="Primary",]
clin_693 <- clin_693[clin_693$IDH_mutation_status %in% c('Wildtype'),]
clin_693 <- clin_693[clin_693$Histology %in% c('GBM'),]


cgga_693RNA_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_693.RSEM-genes.20200506.txt"),check.names = FALSE)
cgga_693RNA_raw[is.na(cgga_693RNA_raw)] <- 0

cgga_693RNA_raw <- cgga_693RNA_raw[cgga_693RNA_raw$Gene_Name!='',]
cgga_693RNA_raw <- cgga_693RNA_raw[!duplicated(cgga_693RNA_raw$Gene_Name),]

rownames(cgga_693RNA_raw) <- cgga_693RNA_raw$Gene_Name

cgga_693RNA <- as.data.frame(t(cgga_693RNA_raw[-1]))
row.names(clin_693) <- clin_693$CGGA_ID
# Align clinical data:
cgga_693RNA <- cgga_693RNA[str_sub(row.names(cgga_693RNA)) %in% row.names(clin_693), ]
cgga_693RNA_log2 <- apply(cgga_693RNA, c(1, 2), function(value) log2(value + 1))
cgga_693RNA <- as.data.frame(scale(cgga_693RNA_log2, center = TRUE, scale = TRUE))
```

```{r CGGA 325}
#clin
clin_325_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_325_clinical.20200506.txt"), sep = '\t')
clin_325 <- clin_325_raw[clin_325_raw$PRS_type =="Primary",]
clin_325 <- clin_325[clin_325$IDH_mutation_status %in% c('Wildtype'),]
clin_325 <- clin_325[clin_325$Histology %in% c('GBM'),]
#RNA
cgga_325RNA_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_325.RSEM-genes.20200506.txt"),check.names = FALSE)
cgga_325RNA_raw[is.na(cgga_325RNA_raw)] <- 0

cgga_325RNA_raw <- cgga_325RNA_raw[cgga_325RNA_raw$Gene_Name!='',]
cgga_325RNA_raw <- cgga_325RNA_raw[!duplicated(cgga_325RNA_raw$Gene_Name),]

rownames(cgga_325RNA_raw) <- cgga_325RNA_raw$Gene_Name

cgga_325RNA <- as.data.frame(t(cgga_325RNA_raw[-1]))
row.names(clin_325) <- clin_325$CGGA_ID

# Align clinical data:
cgga_325RNA <- cgga_325RNA[row.names(cgga_325RNA) %in% row.names(clin_325), ]

cgga_325RNA_log2 <- apply(cgga_325RNA, c(1, 2), function(value) log2(value + 1))
cgga_325RNA <- as.data.frame(scale(cgga_325RNA_log2, center = TRUE, scale = TRUE))
```

```{r Merging dfs}
#Genes
head(colnames(cgga_325RNA))
head(colnames(cgga_693RNA))
head(colnames(tcga_RNA))
cgga_693RNA
common_genes <- intersect(colnames(cgga_325RNA), colnames(cgga_693RNA))
common_genes<- intersect(common_genes, colnames(tcga_RNA))
cgga_693RNA[,common_genes]

stv <- read_excel('/home/jing/Phd_project/project_GBM/gbm_OUTPUT/gbm_OUTPUT_LINCS/ALL_DATA_2020_Jing_gbm_del.xlsx',
                  sheet = 'STVs')
lincs_genes <- intersect(common_genes, stv$Gene)

#clin columns
tcga_clin$Gender <- tcga_clin$SEX
tcga_clin$Age <- tcga_clin$AGE
tcga_clin$Censor..alive.0..dead.1. <- tcga_clin$OS_STATUS
tcga_clin$OS <- tcga_clin$OS_MONTHS*30
colnames(tcga_clin)
common_columns <- c('Gender','Age','Censor..alive.0..dead.1.','OS')

comb_clin <- list(tcga_clin, clin_325, clin_693)
comb_clin <- do.call(rbind, lapply(comb_clin, function(x) x[,common_columns, drop = FALSE]))

#RNA
RNA_combined <- rbind(
  tcga_RNA[, common_genes, drop = FALSE],
  cgga_325RNA[, common_genes, drop = FALSE],
  cgga_693RNA[, common_genes, drop = FALSE]
)


surv_obj <- Surv(time = comb_clin$OS, 
                 event = comb_clin$Censor..alive.0..dead.1.=="1")
#surv_obj 
fit <- survfit(surv_obj ~ 1, data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival", surv.median.line = 'hv',risk.table = TRUE)

summary(fit)$table["median"]
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival", 
                surv.median.line = 'hv', risk.table = TRUE)
comb_clin$Gender <- trimws(comb_clin$Gender)

fit <- survfit(surv_obj ~ Gender , data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Month", ylab = "Overall survival",pval = TRUE,
           risk.table =TRUE)

```



```{r}
# fit multivariate model (COX proportional hazard) 
fit.coxph <- coxph(surv_obj ~ EGFR + ERBB2 + ERBB3 + ERBB4 + NRG1 + NRG2 + NRG3 + NRG4, 
                   data = RNA_combined)

ggforest(fit.coxph, data = RNA_combined)
#new.coxph <- predict(fit.coxph, newdata = RNA[,c("KRAS", "ERBB2")])
#new.coxph
fit.coxph <- coxph(surv_obj ~ KSR1 + KSR2 + IQGAP1 + GAB1 + GAB2, 
                   data = RNA_combined)
ggforest(fit.coxph, data = RNA_combined)

fit.coxph <- coxph(surv_obj ~ Gender + Age , data = comb_clin)
ggforest(fit.coxph, data = comb_clin)
```

```{r progeny}
library(progeny)
zscores = as.matrix(t(RNA_combined))
pathways <- progeny(zscores, scale=TRUE, organism="Human")  #, top = 100, perm = 1)
path_df = as.data.frame(pathways)
# fit multivariate model (COX proportional hazard) 
colnames(path_df)


fit.coxph <- coxph(surv_obj ~  EGFR + Hypoxia   + TGFb  + `JAK-STAT` + TNFa, 
                   data = path_df)
ggforest(fit.coxph, data = path_df)


fit.coxph <- coxph(surv_obj ~ NFkB + Androgen +  VEGF + `JAK-STAT` + TGFb, 
                   data = path_df)
ggforest(fit.coxph, data = path_df)

fit.coxph <- coxph(surv_obj ~ MAPK + PI3K  +  p53 + TGFb  + `JAK-STAT` + TNFa + 
                     WNT + Androgen +  Estrogen + Hypoxia +  Trail + VEGF, 
                   data = path_df)
ggforest(fit.coxph, data = path_df)

fit.coxph <- coxph(surv_obj ~ Androgen + EGFR + Estrogen + Hypoxia + `JAK-STAT` + 
                     MAPK + NFkB + p53 + PI3K + TGFb + TNFa + Trail + VEGF + WNT,
                   data = path_df)

ggforest(fit.coxph, data = path_df)




# now creating object without zero times
comb_clin_filt <- comb_clin[comb_clin$OS > 0,]
RNA_combined_filt <- RNA_combined[comb_clin$OS > 0,]
path_filt <- path_df[!is.na(comb_clin$OS) & comb_clin$OS > 0, ]


# create a survival object consisting of times & censoring
surv_filt <- Surv(time = comb_clin$OS, 
                 event = comb_clin$Censor..alive.0..dead.1.=="1")
fit <- survfit(surv_filt ~ 1, data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival")

which(is.na(surv_filt))
paste(which(is.na(surv_filt)),collapse = ' , ')


RNA_combined_filt[is.na(RNA_combined_filt)] <- 0

surv_filt <-surv_filt[-c(207 , 225 , 227 , 231),]
RNA_combined_filt <- RNA_combined_filt[-c(207 , 225 , 227 , 231),]
comb_clin_filt<-comb_clin_filt[-c(207 , 225 , 227 , 231),]
path_filt <-path_df[-c(207 , 225 , 227 , 231),]

fit.coxph <- coxph(surv_filt ~  EGFR + Hypoxia   + TGFb  + `JAK-STAT` + TNFa, 
                   data = path_filt)
ggforest(fit.coxph, data = path_filt)

fit.coxph <- coxph(surv_filt ~  MAPK+NFkB+p53+PI3K+TGFb, 
                   data = path_filt)
ggforest(fit.coxph, data = path_filt)

```

```{r GLM}
library("glmpath")
library("glmnet")
library("penalized")
fit_glm <- glmnet(RNA_combined_filt,surv_filt,family="cox") # , alpha = 1, standardize = TRUE, maxit = 1000
print(fit_glm)

cvfit <- cv.glmnet(data.matrix(RNA_combined_filt),surv_filt,family="cox")
plot(cvfit)

cfs = coef(fit_glm,s= 0.002631)

meaning_coefs = rownames(cfs)[cfs[,1]!= 0]
meaning_vals = cfs[cfs[,1]!=0,]
#write.csv(meaning_vals,file=paste0(outdir,'gbm_survival_coeffs_full.csv'))

length(meaning_vals)

coef_data <-data.frame(variable=meaning_coefs,coefficient=meaning_vals)

sorted_coef_abs <- coef_data[order(-coef_data$coefficient,decreasing = TRUE), ]
sorted_coef_abs
top_100 <- tail(sorted_coef_abs,15)
list(top_100$variable)

print(paste(meaning_coefs,collapse=" + "))
ncut = 15
vals_surv = sort(abs(meaning_vals))[1:ncut]
print(paste(top_100$variable,collapse=" + "))
# if we want to run coxph we have to copy-paste the string
fit.coxph <- coxph(surv_filt ~ THBS1 + MUC5B + MXRA5 + DMC1 + GLDN + EGF + GLI3 + HIST1H2AK + RGPD5 + OMA1 + ISLR2 + YAF2 + RAB25 + DCP1A + TNMD, data = RNA_combined_filt)
ggforest(fit.coxph, data = RNA_combined_filt)


top_100 <- tail(sorted_coef_abs,15)
list(coef_data$variable)
# Assuming top_100 is a data frame containing the top 100 coefficients
paste(coef_data$variable, collapse = "+")


# Create bar plot
ggplot(top_100, aes(x = reorder(variable, coefficient), y = coefficient)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() +  # Rotate axis labels
  labs(title = "Coefficients from glmnet Model", 
       x = "Genes", y = "Coefficient") +
  theme_minimal()

```
```{r}
#tcga rsem 
tcga_rna_raw <- read.delim(paste0(wkdir,"gbm_DATA_TCGA/data_mrna_seq_v2_rsem.txt"),check.names = FALSE)
tcga_rna_raw[is.na(tcga_rna_raw)] <- 0

tcga_rna <- tcga_rna_raw[tcga_rna_raw$Hugo_Symbol!='',]
tcga_rna <- tcga_rna[!duplicated(tcga_rna$Hugo_Symbol),]
rownames(tcga_rna) <- tcga_rna$Hugo_Symbol
tcga_rna <- as.data.frame(t(tcga_rna[-1:-2]))

#retrieve RNAs of interest
tcga_rna <- tcga_rna[str_sub(row.names(tcga_rna), end = -4) %in% row.names(tcga_clin), ]

max(tcga_rna)
min(tcga_rna)

tcga_rna_log2 <- apply(tcga_rna, c(1, 2), function(value) log2(value + 1))
min(tcga_rna_log2) #0
max(tcga_rna_log2) #19.96911

#dot product
tcga_rna_log2_subset <- tcga_rna_log2[, coef_data$variable]
coef_data_subset <-coef_data[,-1]

result1 <- tcga_rna_log2_subset %*% coef_data_subset
rownames(result1) <- str_sub(row.names(result1), end = -4)

cgga_693RNA_subset <- cgga_693RNA_log2[row.names(cgga_693RNA_log2)%in% row.names(clin_693), ]
cgga_693RNA_subset<- cgga_693RNA_subset[, coef_data$variable]

result2 <- cgga_693RNA_subset %*% coef_data_subset

cgga_325RNA_subset<- cgga_325RNA_log2[, coef_data$variable]
result3 <- cgga_325RNA_subset %*% coef_data_subset
result3

result <- rbind(result1,result2,result3)
#populate values back
comb_clin$DPD_prognosis <- result[str_sub(row.names(result)) %in% row.names(comb_clin), ]


hist(comb_clin$DPD_prognosis)
#assign to positive,negative (I only have positive and decided to select a positive threshold)
comb_clin$outcome <- ifelse(comb_clin$DPD_prognosis > 0, "Positive",
                       ifelse(comb_clin$DPD_prognosis == 0, "0", "Negative"))


### KP and hazard ratio
surv_obj_filt <- Surv(time = comb_clin$OS, 
                 event = comb_clin$Censor..alive.0..dead.1.=="1")

fit <- survfit(surv_obj_filt ~ outcome , data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival",pval = TRUE,
           risk.table =TRUE)


fit.coxph <- coxph(surv_obj_filt ~ Gender + Age +outcome, data = comb_clin)
ggforest(fit.coxph, data = comb_clin)

```
```{r plot}
# surv_plot <- ggsurvplot(
#   fit,
#   data = comb_clin,
#   xlab = "Days",
#   ylab = "Overall survival",
#   pval = TRUE,
#   risk.table = TRUE
# )
# 
# # Save the plot as a PNG
# ggsave(
#   filename = paste0(outdir,"survival_plot.png"),  
#   plot = surv_plot$plot,          
#   device = "png",                
#   width = 8,                     
#   height = 4,                     
#   dpi = 300                      
# )
# 
# ggsave(
#   filename = paste0(outdir,"risk_table.png"),
#   plot = surv_plot$table,         # Use the risk table component
#   device = "png",
#   width = 8,
#   height = 2,
#   dpi = 300
# )
```

```{r Lincs genes}

RNA_combined_lincs <- RNA_combined_filt[,lincs_genes]
fit_glm <- glmnet(RNA_combined_lincs,surv_filt,family="cox") # , alpha = 1, standardize = TRUE, maxit = 1000
print(fit_glm)

cvfit <- cv.glmnet(data.matrix(RNA_combined_filt),surv_filt,family="cox")
plot(cvfit)

cfs = coef(fit_glm,s= 0.001533)

meaning_coefs = rownames(cfs)[cfs[,1]!= 0]
meaning_vals = cfs[cfs[,1]!=0,]


length(meaning_vals)

coef_data <-data.frame(variable=meaning_coefs,coefficient=meaning_vals)

sorted_coef_abs <- coef_data[order(-coef_data$coefficient,decreasing = TRUE), ]
sorted_coef_abs
top_100 <- tail(sorted_coef_abs,15)
list(top_100$variable)

print(paste(meaning_coefs,collapse=" + "))
ncut = 15
vals_surv = sort(abs(meaning_vals))[1:ncut]
print(paste(top_100$variable,collapse=" + "))
# if we want to run coxph we have to copy-paste the string
fit.coxph <- coxph(surv_filt ~ BZW2 + MRPS2 + MAT2A + CSK + CTTN + CHMP4A + KLHL21 + KDM3A + SIRT3 + TCTA + PLP2 + SPRED2 + RAE1 + NMT1 + EGF, data = RNA_combined_filt)
ggforest(fit.coxph, data = RNA_combined_filt)


top_100 <- tail(sorted_coef_abs,15)
list(coef_data$variable)
# Assuming top_100 is a data frame containing the top 100 coefficients
#paste(coef_data$variable, collapse = "+")


# Create bar plot
ggplot(top_100, aes(x = reorder(variable, coefficient), y = coefficient)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() +  # Rotate axis labels
  labs(title = "Coefficients from glmnet Model", 
       x = "Genes", y = "Coefficient") +
  theme_minimal()

```

```{r}
#dot product
tcga_rna_log2_subset <- tcga_rna_log2[, coef_data$variable]
coef_data_subset <-coef_data[,-1]

result1 <- tcga_rna_log2_subset %*% coef_data_subset
rownames(result1) <- str_sub(row.names(result1), end = -4)

cgga_693RNA_subset <- cgga_693RNA_log2[row.names(cgga_693RNA_log2)%in% row.names(clin_693), ]
cgga_693RNA_subset<- cgga_693RNA_subset[, coef_data$variable]

result2 <- cgga_693RNA_subset %*% coef_data_subset

cgga_325RNA_subset<- cgga_325RNA_log2[, coef_data$variable]
result3 <- cgga_325RNA_subset %*% coef_data_subset
result3

result <- rbind(result1,result2,result3)
#populate values back
comb_clin$DPD_prognosis <- result[str_sub(row.names(result)) %in% row.names(comb_clin), ]


hist(comb_clin$DPD_prognosis)
#assign to positive,negative (I only have positive and decided to select a positive threshold)
comb_clin$outcome <- ifelse(comb_clin$DPD_prognosis > 0, "Positive",
                       ifelse(comb_clin$DPD_prognosis == 0, "0", "Negative"))


### KP and hazard ratio
surv_obj_filt <- Surv(time = comb_clin$OS, 
                 event = comb_clin$Censor..alive.0..dead.1.=="1")

fit <- survfit(surv_obj_filt ~ outcome , data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival",pval = TRUE,
           risk.table =TRUE)


fit.coxph <- coxph(surv_obj_filt ~ Gender + Age +outcome, data = comb_clin)
ggforest(fit.coxph, data = comb_clin)

#write.csv(meaning_vals,file=paste0(outdir,'gbm_survival_coeffs_lincs.csv'))

```

```{r plot output}
# surv_plot <- ggsurvplot(
#   fit,
#   data = comb_clin,
#   xlab = "Days",
#   ylab = "Overall survival",
#   pval = TRUE,
#   risk.table = TRUE
# )
# 
# # Save the plot as a PNG
# ggsave(
#   filename = paste0(outdir,"survival_lincs_plot.png"),  
#   plot = surv_plot$plot,          
#   device = "png",                
#   width = 8,                     
#   height = 4,                     
#   dpi = 300                      
# )
# 
# ggsave(
#   filename = paste0(outdir,"risk_table_lincs.png"),
#   plot = surv_plot$table,         # Use the risk table component
#   device = "png",
#   width = 8,
#   height = 2,
#   dpi = 300
# )
```
