---
title: "cgga tcga final"
author: "Jing"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
library(dplyr)
library(ggplot2)
library(stringr)
library(readxl)
```

```{r 693}

wkdir<- "/home/jing/Phd_project/project_GBM/gbm_DATA/"
clin_693_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_693_clinical.20200506.txt"), 
                           sep = '\t')
table(clin_693_raw$IDH_mutation_status)
clin_693 <- clin_693_raw[clin_693_raw$IDH_mutation_status %in% c('Wildtype'),]
clin_693 <- clin_693[clin_693$Grade %in% c('WHO IV'),]
clin_693$Age <- as.integer(clin_693$Age)
clin_693 <- clin_693[clin_693$Age >18,] #Remove pediatric patients

cgga_693RNA_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_693.RSEM-genes.20200506.txt"),check.names = FALSE)
cgga_693RNA_raw[is.na(cgga_693RNA_raw)] <- 0

cgga_693RNA_raw <- cgga_693RNA_raw[cgga_693RNA_raw$Gene_Name!='',]
cgga_693RNA_raw <- cgga_693RNA_raw[!duplicated(cgga_693RNA_raw$Gene_Name),]

rownames(cgga_693RNA_raw) <- cgga_693RNA_raw$Gene_Name

cgga_693RNA <- as.data.frame(t(cgga_693RNA_raw[-1]))
row.names(clin_693) <- clin_693$CGGA_ID
# Align clinical data:
cgga_693RNA <- cgga_693RNA[str_sub(row.names(cgga_693RNA)) %in% row.names(clin_693), ]
cgga_693RNA_log2 <- apply(cgga_693RNA, c(1, 2), function(value) log2(value + 1))
#cgga_693RNA <- as.data.frame(scale(cgga_693RNA_log2, center = TRUE, scale = TRUE))
```

```{r 325}

#clin
clin_325_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_325_clinical.20200506.txt"), sep = '\t')
clin_325 <- clin_325_raw[clin_325_raw$PRS_type !="Secondary",]
clin_325 <- clin_325[clin_325$IDH_mutation_status %in% c('Wildtype'),]
clin_325 <- clin_325[clin_325$Grade %in% c('WHO IV'),]
clin_325$Age <- as.integer(clin_325$Age)
clin_325 <- clin_325[clin_325$Age >18,] #Remove pediatric patients

table(clin_325$IDH_mutation_status)
#RNA
cgga_325RNA_raw <- read.delim(paste0(wkdir,"gbm_DATA_CGGA/CGGA.mRNAseq_325.RSEM-genes.20200506.txt"),check.names = FALSE)
cgga_325RNA_raw[is.na(cgga_325RNA_raw)] <- 0

cgga_325RNA_raw <- cgga_325RNA_raw[cgga_325RNA_raw$Gene_Name!='',]
cgga_325RNA_raw <- cgga_325RNA_raw[!duplicated(cgga_325RNA_raw$Gene_Name),]

rownames(cgga_325RNA_raw) <- cgga_325RNA_raw$Gene_Name

cgga_325RNA <- as.data.frame(t(cgga_325RNA_raw[-1]))
row.names(clin_325) <- clin_325$CGGA_ID

# Align clinical data:
cgga_325RNA <- cgga_325RNA[row.names(cgga_325RNA) %in% row.names(clin_325), ]
cgga_325RNA_log2 <- apply(cgga_325RNA, c(1, 2), function(value) log2(value + 1))

#cgga_325RNA <- as.data.frame(scale(cgga_325RNA_log2, center = TRUE, scale = TRUE))

```

```{r RNA combine}

common_genes <- intersect(colnames(cgga_325RNA), colnames(cgga_693RNA))

comb_clin <- rbind(clin_325, clin_693)
comb_clin$Gender <- trimws(comb_clin$Gender)

#RNA
common_genes <- intersect(colnames(cgga_693RNA_log2), colnames(cgga_325RNA_log2))#23271

# Step 3: Subset to common genes
cgga_693RNA_subset <- cgga_693RNA_log2[, common_genes, drop = FALSE]
cgga_325RNA_subset <- cgga_325RNA_log2[, common_genes, drop = FALSE]

# Step 4: Merge datasets by rows
RNA_combined <- rbind(cgga_693RNA_subset, cgga_325RNA_subset)

# Step 5: Apply z-scale to the merged dataset
RNA_combined <- scale(RNA_combined, center = TRUE, scale = TRUE)

RNA_combined <- as.data.frame(RNA_combined)

```

```{r}

surv_obj <- Surv(time = comb_clin$OS, 
                 event = comb_clin$Censor..alive.0..dead.1.=="1")
#surv_obj 
fit <- survfit(surv_obj ~ 1, data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival", surv.median.line = 'hv',risk.table = TRUE)

summary(fit)$table["median"]
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival", 
           surv.median.line = 'hv', risk.table = TRUE)
comb_clin$Gender <- trimws(comb_clin$Gender)

fit <- survfit(surv_obj ~ Gender , data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Month", ylab = "Overall survival",pval = TRUE,
           risk.table =TRUE)
```

```{r Progeny}
library(progeny)
zscores = as.matrix(t(RNA_combined))
pathways <- progeny(zscores, scale=TRUE, organism="Human")  #, top = 100, perm = 1)
path_df = as.data.frame(pathways)
# fit multivariate model (COX proportional hazard) 
colnames(path_df)

comb_clin_filt <- comb_clin[comb_clin$OS > 0,]
RNA_combined_filt <- RNA_combined[comb_clin$OS > 0,]
path_filt <- path_df[!is.na(comb_clin$OS) & comb_clin$OS > 0, ]


# create a survival object consisting of times & censoring
surv_filt <- Surv(time = comb_clin$OS, 
                  event = comb_clin$Censor..alive.0..dead.1.=="1")
fit <- survfit(surv_filt ~ 1, data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival")

which(is.na(surv_filt))
paste(which(is.na(surv_filt)),collapse = ' , ')



```

```{r}

RNA_combined_filt[is.na(RNA_combined_filt)] <- 0

surv_filt <-surv_filt[-c(107 , 144 , 172 , 174 , 183 , 236 , 244 , 266),]
RNA_combined_filt <- RNA_combined_filt[-c(107 , 144 , 172 , 174 , 183 , 236 , 244 , 266),]
comb_clin_filt<-comb_clin_filt[-c(107 , 144 , 172 , 174 , 183 , 236 , 244 , 266),]
path_filt <-path_df[-c(107 , 144 , 172 , 174 , 183 , 236 , 244 , 266),]

fit.coxph <- coxph(surv_filt ~  EGFR + Hypoxia   + TGFb  + `JAK-STAT` + TNFa, 
                   data = path_filt)
ggforest(fit.coxph, data = path_filt)

fit.coxph <- coxph(surv_filt ~  MAPK+NFkB+p53+PI3K+TGFb, 
                   data = path_filt)
ggforest(fit.coxph, data = path_filt)
```

```{r}

library("glmpath")
library("glmnet")
library("penalized")

# glmnet over progeny
fit_glm <- glmnet(path_filt,surv_filt,family="cox") # , alpha = 1, standardize = TRUE, maxit = 1000
print(fit_glm)
# analysing results
cfs = coef(fit_glm,s=0.007992) #27 13 0.56 0.007992

meaning_coefs = rownames(cfs)[cfs[,1]!= 0]
meaning_vals = cfs[cfs[,1]!=0,]


coef_data <-data.frame(variable=meaning_coefs,coefficient=meaning_vals)
# Create bar plot
ggplot(coef_data, aes(x = reorder(variable, coefficient), y = coefficient)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() +  # Rotate axis labels
  labs(title = "Coefficients from glmnet Model", 
       x = "Pathways", y = "Coefficient") +
  theme_minimal()

#Full gene set
fit_glm <- glmnet(RNA_combined_filt, surv_filt, family="cox")# , alpha = 1, standardize = TRUE, maxit = 1000)
print(fit_glm)

cvfit <- cv.glmnet(data.matrix(RNA_combined_filt),surv_filt,family="cox",type.measure = 'C')
plot(cvfit)

cfs = coef(fit_glm,s= 0.002107)

meaning_coefs = rownames(cfs)[cfs[,1]!= 0]
meaning_vals = cfs[cfs[,1]!=0,]
#write.csv(meaning_vals,file=paste0(outdir,'gbm_survival_coeffs_full.csv'))

length(meaning_vals)
coef_data <-data.frame(variable=meaning_coefs,coefficient=meaning_vals)


cgga_693RNA_subset <- cgga_693RNA_log2[row.names(cgga_693RNA_log2)%in% row.names(clin_693), ]
cgga_693RNA_subset<- cgga_693RNA_subset[, coef_data$variable]
coef_data_subset <- coef_data[,-1]
result2 <- cgga_693RNA_subset %*% coef_data_subset

cgga_325RNA_subset<- cgga_325RNA_log2[, coef_data$variable]
result3 <- cgga_325RNA_subset %*% coef_data_subset

result <- rbind(result2,result3)
#populate values back

comb_clin$DPD_prognosis <- result[str_sub(row.names(result)) %in% row.names(comb_clin), ]


hist(comb_clin$DPD_prognosis)
#assign to positive,negative (I only have positive and decided to select a positive threshold)
comb_clin$outcome <- ifelse(comb_clin$DPD_prognosis > 0, "Positive",
                            ifelse(comb_clin$DPD_prognosis == 0, "0", "Negative"))


### KP and hazard ratio
surv_obj_filt <- Surv(time = comb_clin$OS, 
                      event = comb_clin$Censor..alive.0..dead.1.=="1")

fit <- survfit(surv_obj_filt ~ outcome , data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival",pval = TRUE,
           risk.table =TRUE)



fit.coxph <- coxph(surv_obj_filt ~ Gender + Age +Histology+outcome , data = comb_clin)
ggforest(fit.coxph, data = comb_clin)


forest_plot <- ggforest(fit.coxph, data = comb_clin)

#Conclusions: full gene set not necessarily better


#Using previous STV from TCGA, to check if it applies to CGGA
common_genes <- intersect(colnames(RNA_combined_filt), stv$Gene)

cgga_693RNA_subset <- cgga_693RNA_log2[row.names(cgga_693RNA_log2)%in% row.names(clin_693), ]
cgga_693RNA_subset<- cgga_693RNA_subset[, common_genes]

result2 <- cgga_693RNA_subset %*% vector


cgga_325RNA_subset<- cgga_325RNA_log2[, common_genes]
result3 <- cgga_325RNA_subset %*% vector

result <- rbind(result2,result3)
#populate values back

comb_clin$DPD_prognosis <- result[str_sub(row.names(result)) %in% row.names(comb_clin), ]


hist(comb_clin$DPD_prognosis)
#assign to positive,negative (I only have positive and decided to select a positive threshold)
comb_clin$outcome <- ifelse(comb_clin$DPD_prognosis > 0, "Positive",
                            ifelse(comb_clin$DPD_prognosis == 0, "0", "Negative"))


### KP and hazard ratio
surv_obj_filt <- Surv(time = comb_clin$OS, 
                      event = comb_clin$Censor..alive.0..dead.1.=="1")

fit <- survfit(surv_obj_filt ~ outcome , data = comb_clin)
ggsurvplot(fit, data = comb_clin, xlab = "Days", ylab = "Overall survival",pval = TRUE,
           risk.table =TRUE)



fit.coxph <- coxph(surv_obj_filt ~ Gender + Age +Histology+outcome , data = comb_clin)
ggforest(fit.coxph, data = comb_clin)


forest_plot <- ggforest(fit.coxph, data = comb_clin)

# Save the forest plot as an image
ggsave(paste0(outdir,"forest_plot.png"), plot = forest_plot, width = 10, height = 6, dpi = 300)






```


```{r LINCs data}

```

